#!/usr/bin/env bun
# Generates seed/listicle-operators-metros-2026-08-15.sql
# Source: Firecrawl search + company-site scrapes, 2026-08-15.
# Only companies with a public phone on their own site (or a confirmed SERP
# phone after the company site was scraped and confirmed as a local hauler).

from pathlib import Path

NOTES = (
    "Firecrawl web research 2026-08-15: public phone/website from company site. "
    "Local hauler (not a national broker). Phone call for insurance/license still "
    "recommended before paid ads."
)

# city_id, name, state, lat, lng
CITIES = {
    "city-oklahoma-city": ("Oklahoma City", "OK", 35.4676, -97.5164),
    "city-tulsa": ("Tulsa", "OK", 36.1540, -95.9928),
    "city-chicago": ("Chicago", "IL", 41.8781, -87.6298),
    "city-new-york": ("New York", "NY", 40.7128, -74.0060),
    "city-philadelphia": ("Philadelphia", "PA", 39.9526, -75.1652),
    "city-seattle": ("Seattle", "WA", 47.6062, -122.3321),
    "city-charlotte": ("Charlotte", "NC", 35.2271, -80.8431),
    "city-nashville": ("Nashville", "TN", 36.1627, -86.7816),
    "city-boston": ("Boston", "MA", 42.3601, -71.0589),
    "city-columbus": ("Columbus", "OH", 39.9612, -82.9988),
    "city-indianapolis": ("Indianapolis", "IN", 39.7684, -86.1581),
    "city-detroit": ("Detroit", "MI", 42.3314, -83.0458),
    "city-minneapolis": ("Minneapolis", "MN", 44.9778, -93.2650),
    "city-kansas-city": ("Kansas City", "MO", 39.0997, -94.5786),
    "city-las-vegas": ("Las Vegas", "NV", 36.1699, -115.1398),
    "city-portland": ("Portland", "OR", 45.5152, -122.6784),
    "city-san-antonio": ("San Antonio", "TX", 29.4241, -98.4936),
    "city-jacksonville": ("Jacksonville", "FL", 30.3322, -81.6557),
    "city-san-francisco": ("San Francisco", "CA", 37.7749, -122.4194),
    "city-washington": ("Washington", "DC", 38.9072, -77.0369),
    "city-phoenix": ("Phoenix", "AZ", 33.4484, -112.0740),
    "city-baltimore": ("Baltimore", "MD", 39.2904, -76.6122),
    "city-birmingham": ("Birmingham", "AL", 33.5186, -86.8104),
    "city-louisville": ("Louisville", "KY", 38.2527, -85.7585),
    "city-new-orleans": ("New Orleans", "LA", 29.9511, -90.0715),
    "city-providence": ("Providence", "RI", 41.8236, -71.4222),
    "city-hartford": ("Hartford", "CT", 41.7658, -72.6734),
    "city-sioux-falls": ("Sioux Falls", "SD", 43.5446, -96.7311),
    "city-manchester": ("Manchester", "NH", 42.9956, -71.4548),
}

# Each operator: only included after Firecrawl scrape confirmed local roll-off + phone.
OPS = [
    # Oklahoma City — enough for a state listicle with Tulsa
    {
        "id": "op-fc15-okc-enviro",
        "name": "Enviro Dispose",
        "slug": "enviro-dispose",
        "phone": "405-213-4593",
        "email": "dustin@envirodispose.com",
        "website": "https://envirodispose.com/",
        "desc": "Locally owned Oklahoma City roll-off hauler with same-day service and 10–40 yard open-top boxes. Yard at 7220 NW 63rd Street in Bethany.",
        "city": "city-oklahoma-city",
        "sizes": [10, 15, 20, 25, 30, 40],
        "materials": ["construction", "mixed", "household", "yard"],
        "pmin": 350, "pmax": 700,
        "driveway": False, "sameday": True,
        "score": 88,
    },
    {
        "id": "op-fc15-okc-cubic",
        "name": "Cubic Waste Solutions",
        "slug": "cubic-waste-solutions",
        "phone": "405-261-9105",
        "email": None,
        "website": "https://cubicwaste.com/",
        "desc": "Family-owned Oklahoma City roll-off contractor with 10–40 yard dumpsters, same-day delivery, and driveway-friendly smaller boxes.",
        "city": "city-oklahoma-city",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household", "concrete"],
        "pmin": 350, "pmax": 750,
        "driveway": True, "sameday": True,
        "score": 87,
    },
    {
        "id": "op-fc15-okc-ready",
        "name": "Ready to Roll Off",
        "slug": "ready-to-roll-off",
        "phone": "405-919-2814",
        "email": "ready2rolloff@gmail.com",
        "website": "https://ready2rolloff.com/",
        "desc": "Family-run OKC roll-off rental with a published $435 20-yard / 10-day package (2 tons included) and same-day delivery across Edmond, Yukon, and Mustang.",
        "city": "city-oklahoma-city",
        "sizes": [20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 435, "pmax": 550,
        "driveway": True, "sameday": True,
        "score": 86,
    },
    {
        "id": "op-fc15-okc-junkfrog",
        "name": "Junk Frog",
        "slug": "junk-frog",
        "phone": "405-444-5865",
        "email": None,
        "website": "https://junkfrog.com/",
        "desc": "Oklahoma City roll-off dumpster rental plus junk removal and storage with flat-rate pricing.",
        "city": "city-oklahoma-city",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 650,
        "driveway": False, "sameday": False,
        "score": 80,
    },
    {
        "id": "op-fc15-okc-payneless",
        "name": "Payne-Less Junk Removal",
        "slug": "payne-less-junk-removal",
        "phone": "405-788-1689",
        "email": None,
        "website": "https://www.okcjunkhauling.com/",
        "desc": "OKC dumpster rental and junk removal with first-ton included packages and same- or next-day service.",
        "city": "city-oklahoma-city",
        "sizes": [15, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 300, "pmax": 600,
        "driveway": False, "sameday": True,
        "score": 79,
    },
    {
        "id": "op-fc15-okc-btdt",
        "name": "Bin There Dump That Oklahoma City",
        "slug": "bin-there-dump-that-oklahoma-city",
        "phone": "405-640-4345",
        "email": None,
        "website": "https://www.okcdumpsterrental.com/",
        "desc": "Driveway-safe trailer-style dumpsters from local franchisees Jason and Heather. Flat-rate 10-day rentals in 6–20 yard sizes.",
        "city": "city-oklahoma-city",
        "sizes": [6, 10, 14, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 700,
        "driveway": True, "sameday": True,
        "score": 76,
    },
    # Tulsa
    {
        "id": "op-fc15-tul-reddirt",
        "name": "Red Dirt Roll-Offs",
        "slug": "red-dirt-roll-offs",
        "phone": "918-955-3867",
        "email": None,
        "website": "https://www.reddirtrolloffs.com/",
        "desc": "Veteran- and firefighter-owned Tulsa roll-off company with published 10-yard ($299) and 15-yard ($349) 10-day rates.",
        "city": "city-tulsa",
        "sizes": [10, 15],
        "materials": ["construction", "mixed", "household", "yard"],
        "pmin": 299, "pmax": 399,
        "driveway": False, "sameday": False,
        "score": 88,
    },
    {
        "id": "op-fc15-tul-atob",
        "name": "A to B Hauling",
        "slug": "a-to-b-hauling",
        "phone": "918-900-4285",
        "email": None,
        "website": "https://atobhauling.com/",
        "desc": "Owner-operated Tulsa roll-off rentals since 2014 with 15–30 yard boxes and same-day delivery when booked before 2 p.m.",
        "city": "city-tulsa",
        "sizes": [15, 20, 25, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 700,
        "driveway": True, "sameday": True,
        "score": 86,
    },
    {
        "id": "op-fc15-tul-awc",
        "name": "American Waste Control",
        "slug": "american-waste-control",
        "phone": "918-446-0023",
        "email": None,
        "website": "https://www.americanwastecontrol.com/",
        "desc": "Tulsa waste, recycling, and roll-off company serving homes and businesses since 1970.",
        "city": "city-tulsa",
        "sizes": [10, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 750,
        "driveway": False, "sameday": False,
        "score": 84,
    },
    {
        "id": "op-fc15-tul-oncall",
        "name": "On Call Services and Rentals",
        "slug": "on-call-services-rentals",
        "phone": "918-397-7787",
        "email": None,
        "website": "https://oncallservicesandrentals.com/roll-off-dumpsters/",
        "desc": "Tulsa-based roll-off, porta-potty, and fencing company with 15–30 yard dumpsters and published tonnage packages.",
        "city": "city-tulsa",
        "sizes": [15, 20, 25, 30],
        "materials": ["construction", "mixed", "household", "yard"],
        "pmin": 325, "pmax": 650,
        "driveway": True, "sameday": True,
        "score": 83,
    },
    {
        "id": "op-fc15-tul-btdt",
        "name": "Bin There Dump That Tulsa West",
        "slug": "bin-there-dump-that-tulsa-west",
        "phone": "918-246-7199",
        "email": None,
        "website": "https://www.bintheredumpthat.com/tulsa-west-dumpster-rentals/",
        "desc": "Locally operated Tulsa West franchise with driveway-friendly trailer dumpsters for residential jobs.",
        "city": "city-tulsa",
        "sizes": [10, 14, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 680,
        "driveway": True, "sameday": False,
        "score": 75,
    },
    # Chicago
    {
        "id": "op-fc15-chi-brackenbox",
        "name": "Brackenbox",
        "slug": "brackenbox",
        "phone": "708-339-4100",
        "email": None,
        "website": "https://brackenbox.com/",
        "desc": "Chicagoland and northwest Indiana residential and commercial roll-off with 10–30 yard boxes. Hours Mon–Fri 6–4, Sat 7–2.",
        "city": "city-chicago",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household", "roofing", "yard"],
        "pmin": 375, "pmax": 750,
        "driveway": False, "sameday": True,
        "score": 86,
    },
    {
        "id": "op-fc15-chi-r2r",
        "name": "Ready 2 Roll Hauling",
        "slug": "ready-2-roll-hauling",
        "phone": "312-520-3619",
        "email": "info@ready2rollhauling.com",
        "website": "https://www.ready2rollhauling.com/",
        "desc": "Chicago south-suburbs junk removal and roll-off from about $370, with same-day service often available.",
        "city": "city-chicago",
        "sizes": [12, 15, 21],
        "materials": ["construction", "mixed", "household", "yard"],
        "pmin": 370, "pmax": 550,
        "driveway": True, "sameday": True,
        "score": 84,
    },
    {
        "id": "op-fc15-chi-sbc",
        "name": "SBC Waste Solutions",
        "slug": "sbc-waste-solutions",
        "phone": "312-522-1115",
        "email": None,
        "website": "https://www.sbcwastesolutions.com/",
        "desc": "Locally owned Chicago-area hauler offering roll-off, front-load, and recycling across the southwest and west suburbs.",
        "city": "city-chicago",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 375, "pmax": 800,
        "driveway": False, "sameday": False,
        "score": 83,
    },
    {
        "id": "op-fc15-chi-mobile",
        "name": "Mobiledumps Chicagoland",
        "slug": "mobiledumps-chicagoland",
        "phone": "262-202-4507",
        "email": None,
        "website": "https://mobiledumps.com/locations/il/chicagoland/",
        "desc": "Locally owned 14-yard trailer dumpsters for Greater Chicago suburbs with express delivery windows.",
        "city": "city-chicago",
        "sizes": [14],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 550,
        "driveway": True, "sameday": True,
        "score": 78,
    },
    # New York
    {
        "id": "op-fc15-nyc-guma",
        "name": "Guma Containers",
        "slug": "guma-containers",
        "phone": "718-928-3024",
        "email": "sales@gumacontainers.com",
        "website": "https://www.gumacontainers.com/",
        "desc": "Minority-owned, family-run NYC roll-off and packer-truck service with 10–30 yard containers.",
        "city": "city-new-york",
        "sizes": [10, 15, 20, 25, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 450, "pmax": 1200,
        "driveway": False, "sameday": True,
        "score": 85,
    },
    {
        "id": "op-fc15-nyc-bestway",
        "name": "Bestway Carting",
        "slug": "bestway-carting",
        "phone": "800-216-1284",
        "email": None,
        "website": "https://www.bestwaycarting.com/",
        "desc": "Brooklyn, Queens, and NYC carting company with 30+ years of container rentals and construction debris service. HQ in Little Neck.",
        "city": "city-new-york",
        "sizes": [10, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 500, "pmax": 1300,
        "driveway": False, "sameday": False,
        "score": 80,
    },
    {
        "id": "op-fc15-nyc-action",
        "name": "Action Carting",
        "slug": "action-carting",
        "phone": "866-270-9900",
        "email": None,
        "website": "https://actioncarting.com/",
        "desc": "Licensed NYC commercial waste zone hauler offering roll-off dumpsters across the five boroughs.",
        "city": "city-new-york",
        "sizes": [10, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 500, "pmax": 1400,
        "driveway": False, "sameday": False,
        "score": 79,
    },
    # Philadelphia
    {
        "id": "op-fc15-phl-geppert",
        "name": "Geppert Recycling",
        "slug": "geppert-recycling",
        "phone": "215-842-0122",
        "email": None,
        "website": "https://geppertrecycling.com/",
        "desc": "30+ year Philadelphia waste station and roll-off company serving the city plus Bucks, Chester, Delaware, and Montgomery counties.",
        "city": "city-philadelphia",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 375, "pmax": 800,
        "driveway": True, "sameday": True,
        "score": 86,
    },
    {
        "id": "op-fc15-phl-tswaste",
        "name": "Tri-State Waste",
        "slug": "tri-state-waste",
        "phone": "215-423-5200",
        "email": "info@tswaste.com",
        "website": "https://tswaste.com/",
        "desc": "Philadelphia and South Jersey roll-off hauler with 10–40 yard dumpsters and local dispatch.",
        "city": "city-philadelphia",
        "sizes": [10, 12, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 375, "pmax": 850,
        "driveway": True, "sameday": True,
        "score": 84,
    },
    {
        "id": "op-fc15-phl-reams",
        "name": "Reams Disposal",
        "slug": "reams-disposal",
        "phone": "484-722-8247",
        "email": None,
        "website": "https://reamsdisposal.com/dumpster-rental-philadelphia-pa/",
        "desc": "Philadelphia County dumpster rental for remodels, additions, and cleanouts.",
        "city": "city-philadelphia",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 750,
        "driveway": False, "sameday": False,
        "score": 80,
    },
    # Seattle
    {
        "id": "op-fc15-sea-nw",
        "name": "NW Dumpsters",
        "slug": "nw-dumpsters",
        "phone": "206-866-0688",
        "email": "hello@nwdumpsters.com",
        "website": "https://nwdumpsters.com/",
        "desc": "Locally owned Seattle MBE/DBE roll-off company with 300+ containers and same- or next-day delivery.",
        "city": "city-seattle",
        "sizes": [10, 20, 30, 40],
        "materials": ["construction", "mixed", "household", "concrete"],
        "pmin": 450, "pmax": 900,
        "driveway": False, "sameday": True,
        "score": 88,
    },
    {
        "id": "op-fc15-sea-sound",
        "name": "Sound Hauling",
        "slug": "sound-hauling",
        "phone": "425-400-4285",
        "email": None,
        "website": "https://soundhauling.com/services/dumpster-rental.aspx",
        "desc": "Seattle-area hauling company with 14- and 25-yard roll-offs, published package pricing, and driveway-friendly options.",
        "city": "city-seattle",
        "sizes": [14, 25],
        "materials": ["construction", "mixed", "household"],
        "pmin": 375, "pmax": 525,
        "driveway": True, "sameday": True,
        "score": 83,
    },
    # Charlotte
    {
        "id": "op-fc15-clt-a1",
        "name": "A1 Dumpster Rentals",
        "slug": "a1-dumpster-rentals",
        "phone": "704-391-7030",
        "email": None,
        "website": "https://www.a1dumpsterrentals.com/",
        "desc": "Locally owned Charlotte dumpster and demolition company with 30+ years in North and South Carolina.",
        "city": "city-charlotte",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 700,
        "driveway": False, "sameday": True,
        "score": 86,
    },
    {
        "id": "op-fc15-clt-regency",
        "name": "Regency Hauling",
        "slug": "regency-hauling",
        "phone": "704-593-6378",
        "email": "info@regencyhauling.com",
        "website": "https://regencyhauling.com/",
        "desc": "Charlotte dumpster rental and hauling from WT Harris Blvd with 10–40 yard roll-offs and Monday–Saturday service.",
        "city": "city-charlotte",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household", "roofing"],
        "pmin": 365, "pmax": 550,
        "driveway": False, "sameday": False,
        "score": 85,
    },
    {
        "id": "op-fc15-clt-masters",
        "name": "Roll Off Masters",
        "slug": "roll-off-masters",
        "phone": "980-346-3810",
        "email": None,
        "website": "https://rolloffmastersllc.com/",
        "desc": "Charlotte residential and construction roll-off company with driveway-safe delivery and 15/20/30 yard boxes.",
        "city": "city-charlotte",
        "sizes": [15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 700,
        "driveway": True, "sameday": False,
        "score": 84,
    },
    # Nashville
    {
        "id": "op-fc15-nsh-tnro",
        "name": "Tennessee Rolloff",
        "slug": "tennessee-rolloff",
        "phone": "615-784-4076",
        "email": None,
        "website": "https://tnrolloff.com/",
        "desc": "Metro Nashville licensed roll-off and portable toilet company with same-day delivery and 15–30 yard boxes.",
        "city": "city-nashville",
        "sizes": [15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 700,
        "driveway": True, "sameday": True,
        "score": 85,
    },
    {
        "id": "op-fc15-nsh-jandj",
        "name": "J and J Services",
        "slug": "j-and-j-services",
        "phone": "615-599-7778",
        "email": None,
        "website": "https://www.jandjservices.com/services/commercial/roll-off-dumpster-rental",
        "desc": "Nashville-area commercial and residential roll-off rentals in 10–40 yard sizes.",
        "city": "city-nashville",
        "sizes": [10, 12, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 750,
        "driveway": False, "sameday": False,
        "score": 82,
    },
    {
        "id": "op-fc15-nsh-reddog",
        "name": "Red Dog Dumpsters",
        "slug": "red-dog-dumpsters",
        "phone": "615-933-3300",
        "email": None,
        "website": "https://reddogdumpsters.com/",
        "desc": "Nashville roll-off company with published 10/15/20 yard pricing and free delivery inside a 30-minute radius.",
        "city": "city-nashville",
        "sizes": [10, 15, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 365, "pmax": 515,
        "driveway": False, "sameday": True,
        "score": 81,
    },
    # Boston
    {
        "id": "op-fc15-bos-homestead",
        "name": "Homestead Disposal",
        "slug": "homestead-disposal",
        "phone": "781-320-0516",
        "email": "eric@homestead-disposal.com",
        "website": "https://www.homestead-disposal.com/",
        "desc": "Westwood-based Greater Boston roll-off specialist with 25+ years, driveway-safe 7/10/15 yard boxes, and next-day delivery.",
        "city": "city-boston",
        "sizes": [7, 10, 15],
        "materials": ["construction", "mixed", "household", "roofing", "yard", "concrete"],
        "pmin": 450, "pmax": 750,
        "driveway": True, "sameday": True,
        "score": 88,
    },
    {
        "id": "op-fc15-bos-viking",
        "name": "Viking Disposal",
        "slug": "viking-disposal",
        "phone": "781-716-7400",
        "email": None,
        "website": "https://vikingdisposalserv.com/services/roll-off-dumpster/",
        "desc": "Greater Boston roll-off and recycling with 10–30 yard dumpsters and same-day service when inventory allows.",
        "city": "city-boston",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 400, "pmax": 800,
        "driveway": False, "sameday": True,
        "score": 80,
    },
    # Columbus
    {
        "id": "op-fc15-cmh-affordable",
        "name": "Affordable Dumpsters",
        "slug": "affordable-dumpsters-columbus",
        "phone": "614-476-3626",
        "email": None,
        "website": "https://www.affordabledumping.com/",
        "desc": "Franklin County roll-off and trailer dumpsters since 1995. Published rates from $225 with same-day delivery.",
        "city": "city-columbus",
        "sizes": [10, 14, 15, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 225, "pmax": 400,
        "driveway": True, "sameday": True,
        "score": 87,
    },
    {
        "id": "op-fc15-cmh-midohio",
        "name": "Mid-Ohio Dumpsters",
        "slug": "mid-ohio-dumpsters",
        "phone": "614-721-7777",
        "email": "sales@midohiodumpsters.com",
        "website": "https://www.midohiodumpsters.com/",
        "desc": "Family-owned Columbus dumpster, demolition, and junk company with 10–30 yard roll-offs.",
        "city": "city-columbus",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 650,
        "driveway": False, "sameday": False,
        "score": 86,
    },
    {
        "id": "op-fc15-cmh-frog",
        "name": "Frog Hauling",
        "slug": "frog-hauling",
        "phone": "614-258-3764",
        "email": None,
        "website": "https://froghauling.com/",
        "desc": "Columbus flat-rate dumpster rental with same-day delivery when ordered before 1 p.m. Serves Dublin, Westerville, and Upper Arlington.",
        "city": "city-columbus",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 305, "pmax": 425,
        "driveway": True, "sameday": True,
        "score": 85,
    },
    # Indianapolis
    {
        "id": "op-fc15-indy-aa",
        "name": "A and A Roll Offs",
        "slug": "a-and-a-roll-offs",
        "phone": "317-680-3867",
        "email": None,
        "website": "https://www.aarolloffs.com/",
        "desc": "Central Indiana roll-off company with published 12–30 yard rates from $325 and same-day delivery.",
        "city": "city-indianapolis",
        "sizes": [12, 15, 20, 25, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 525,
        "driveway": False, "sameday": True,
        "score": 86,
    },
    {
        "id": "op-fc15-indy-hoosier",
        "name": "Hoosier Hauler",
        "slug": "hoosier-hauler",
        "phone": "317-838-8302",
        "email": None,
        "website": "https://hoosierhauler.com/",
        "desc": "Indianapolis dumpster rental for 25+ years with 10–40 yard roll-offs and portable restrooms.",
        "city": "city-indianapolis",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 700,
        "driveway": True, "sameday": False,
        "score": 85,
    },
    {
        "id": "op-fc15-indy-greenway",
        "name": "Greenway Dumpsters",
        "slug": "greenway-dumpsters",
        "phone": "317-617-9464",
        "email": None,
        "website": "https://greenwaydumpsters.com/",
        "desc": "Indianapolis 10–30 yard roll-off rentals for homes and contractors.",
        "city": "city-indianapolis",
        "sizes": [10, 15, 20, 25, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 650,
        "driveway": False, "sameday": False,
        "score": 83,
    },
    # Detroit
    {
        "id": "op-fc15-det-dumpday",
        "name": "Dump Day Dumpster Rental",
        "slug": "dump-day-dumpster-rental",
        "phone": "313-918-4880",
        "email": "dumpdaydumpsters@gmail.com",
        "website": "https://www.dumpdaydumpsterrental.com/",
        "desc": "Locally owned Metro Detroit rubber-wheeled dumpsters with clear tonnage packages and same-day options.",
        "city": "city-detroit",
        "sizes": [10, 20],
        "materials": ["construction", "mixed", "household", "roofing"],
        "pmin": 350, "pmax": 450,
        "driveway": True, "sameday": True,
        "score": 88,
    },
    {
        "id": "op-fc15-det-dd",
        "name": "Detroit Dumpsters",
        "slug": "detroit-dumpsters",
        "phone": "313-246-8878",
        "email": None,
        "website": "https://www.detroitdumpsters.com/",
        "desc": "Detroit roll-off rentals in 10–40 yard sizes serving Dearborn, Grosse Pointe, and Ann Arbor with same-day when available.",
        "city": "city-detroit",
        "sizes": [10, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 250, "pmax": 800,
        "driveway": True, "sameday": True,
        "score": 80,
    },
    # Minneapolis
    {
        "id": "op-fc15-msp-a1",
        "name": "A-1 Hauling and Rolloffs",
        "slug": "a-1-hauling-and-rolloffs",
        "phone": "763-444-6992",
        "email": None,
        "website": "https://a1rolloffs.com/",
        "desc": "Twin Cities roll-off company with driveway-safe dumpsters, 10–40 yard sizes, and published rates from about $435.",
        "city": "city-minneapolis",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household", "concrete"],
        "pmin": 435, "pmax": 715,
        "driveway": True, "sameday": True,
        "score": 86,
    },
    {
        "id": "op-fc15-msp-nordic",
        "name": "Nordic Waste",
        "slug": "nordic-waste",
        "phone": "612-816-8500",
        "email": None,
        "website": "https://nordic-waste.com/",
        "desc": "Minneapolis–St. Paul roll-off hauler with flat-rate pricing and live local dispatch.",
        "city": "city-minneapolis",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household", "roofing"],
        "pmin": 375, "pmax": 700,
        "driveway": True, "sameday": False,
        "score": 84,
    },
    {
        "id": "op-fc15-msp-american",
        "name": "American Dumpster Rental and Recycling",
        "slug": "american-dumpster-rental-mn",
        "phone": "651-442-8960",
        "email": None,
        "website": "https://www.americandumpstermn.com/",
        "desc": "Twin Cities dumpster rental and recycling for residential and contractor jobs.",
        "city": "city-minneapolis",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 375, "pmax": 700,
        "driveway": False, "sameday": False,
        "score": 81,
    },
    {
        "id": "op-fc15-msp-haulit",
        "name": "Haul It A Day",
        "slug": "haul-it-a-day",
        "phone": "651-615-4423",
        "email": None,
        "website": "https://www.haulitaday.com/",
        "desc": "Twin Cities dumpster service with 10/15/20 yard roll-offs.",
        "city": "city-minneapolis",
        "sizes": [10, 15, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 650,
        "driveway": False, "sameday": False,
        "score": 80,
    },
    # Kansas City
    {
        "id": "op-fc15-kc-uloadit",
        "name": "U-LOAD-IT Dumpsters",
        "slug": "u-load-it-dumpsters",
        "phone": "816-537-5623",
        "email": None,
        "website": "https://uloaditkc.com/",
        "desc": "Locally owned Kansas City dumpster rental since 1997 with same-day service and 1,000+ five-star reviews.",
        "city": "city-kansas-city",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 700,
        "driveway": False, "sameday": True,
        "score": 87,
    },
    {
        "id": "op-fc15-kc-trashbox",
        "name": "The Trash Box",
        "slug": "the-trash-box",
        "phone": "816-875-0028",
        "email": None,
        "website": "https://thetrashboxkc.com/",
        "desc": "Kansas City roll-off company with published 12–20 yard rates from $299 and same-day claims.",
        "city": "city-kansas-city",
        "sizes": [12, 15, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 299, "pmax": 399,
        "driveway": False, "sameday": True,
        "score": 84,
    },
    {
        "id": "op-fc15-kc-disposal",
        "name": "KC Disposal",
        "slug": "kc-disposal",
        "phone": "816-388-9739",
        "email": "kcdisposal@gmail.com",
        "website": "https://kansascitydisposal.com/",
        "desc": "Kansas City dumpster rentals for residential and contractor jobs.",
        "city": "city-kansas-city",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 650,
        "driveway": False, "sameday": False,
        "score": 82,
    },
    # Las Vegas
    {
        "id": "op-fc15-las-western",
        "name": "Western Elite",
        "slug": "western-elite",
        "phone": "702-605-0655",
        "email": None,
        "website": "https://westernelite.com/",
        "desc": "Las Vegas, Henderson, and Summerlin dumpster rental with a same-day delivery guarantee on 15–40 yard boxes.",
        "city": "city-las-vegas",
        "sizes": [15, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 800,
        "driveway": True, "sameday": True,
        "score": 84,
    },
    {
        "id": "op-fc15-las-grizzly",
        "name": "Grizzly Hauling and Junk",
        "slug": "grizzly-hauling-and-junk",
        "phone": "702-628-7929",
        "email": None,
        "website": "https://www.grizzlyhaulingandjunk.com/",
        "desc": "Las Vegas local hauling and roll-off with 10–40 yard dumpsters and driveway-friendly options.",
        "city": "city-las-vegas",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 750,
        "driveway": True, "sameday": True,
        "score": 83,
    },
    # Portland
    {
        "id": "op-fc15-pdx-oregonrec",
        "name": "Oregon Recycling",
        "slug": "oregon-recycling",
        "phone": "503-720-2281",
        "email": "sales@oregon-recycling.com",
        "website": "https://oregon-recycling.com/",
        "desc": "Portland dumpster rental and junk removal with 15–25 yard roll-offs and published package pricing.",
        "city": "city-portland",
        "sizes": [15, 20, 25],
        "materials": ["construction", "mixed", "household"],
        "pmin": 275, "pmax": 475,
        "driveway": True, "sameday": True,
        "score": 82,
    },
    {
        "id": "op-fc15-pdx-bc",
        "name": "BC Haulers",
        "slug": "bc-haulers",
        "phone": "971-301-5033",
        "email": None,
        "website": "https://www.bchaulers.com/",
        "desc": "Portland and Salem junk removal, demolition, and roll-off dumpsters with a published 21-yard package.",
        "city": "city-portland",
        "sizes": [15, 21],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 550,
        "driveway": False, "sameday": False,
        "score": 80,
    },
    # San Antonio
    {
        "id": "op-fc15-sat-southtx",
        "name": "South Texas Dumpsters",
        "slug": "south-texas-dumpsters",
        "phone": "210-372-8666",
        "email": None,
        "website": "https://southtexasdumpsters.com/",
        "desc": "San Antonio roll-off company with 20–40 yard dumpsters for homes and construction sites.",
        "city": "city-san-antonio",
        "sizes": [20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 750,
        "driveway": False, "sameday": False,
        "score": 83,
    },
    {
        "id": "op-fc15-sat-txro",
        "name": "TX Roll Offs",
        "slug": "tx-roll-offs",
        "phone": "210-903-3333",
        "email": None,
        "website": "https://txrolloffs.com/",
        "desc": "San Antonio dumpster rental and roll-off service with 20–40 yard containers.",
        "city": "city-san-antonio",
        "sizes": [20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 750,
        "driveway": False, "sameday": False,
        "score": 81,
    },
    # Jacksonville
    {
        "id": "op-fc15-jax-american",
        "name": "American Rolloffs",
        "slug": "american-rolloffs",
        "phone": "904-605-1600",
        "email": None,
        "website": "https://american-rolloffs.com/",
        "desc": "Northeast Florida same- or next-day roll-off delivery with 10–40 yard dumpsters and 14-day rentals.",
        "city": "city-jacksonville",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 750,
        "driveway": False, "sameday": True,
        "score": 85,
    },
    {
        "id": "op-fc15-jax-904",
        "name": "904 Dumpster",
        "slug": "904-dumpster",
        "phone": "904-240-5598",
        "email": None,
        "website": "https://www.904dumpster.com/",
        "desc": "Jacksonville dumpster rental starting at $299 with delivery, pickup, and disposal included on 10/15/20 yard boxes.",
        "city": "city-jacksonville",
        "sizes": [10, 15, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 299, "pmax": 550,
        "driveway": False, "sameday": True,
        "score": 83,
    },
    {
        "id": "op-fc15-jax-shapells",
        "name": "Shapell's Inc",
        "slug": "shapells-inc",
        "phone": "904-786-5503",
        "email": None,
        "website": "https://www.shapells.com/",
        "desc": "Jacksonville waste-management company offering roll-off dumpster rentals for homes and contractors.",
        "city": "city-jacksonville",
        "sizes": [10, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 750,
        "driveway": False, "sameday": False,
        "score": 80,
    },
    # San Francisco
    {
        "id": "op-fc15-sf-citywide",
        "name": "Citywide Debris Box and Recycling",
        "slug": "citywide-debris-box",
        "phone": "415-822-3688",
        "email": None,
        "website": "https://www.citywidedebrisbox.com/",
        "desc": "San Francisco Bay Area debris-box hauler specializing in construction and demolition material.",
        "city": "city-san-francisco",
        "sizes": [10, 20, 30, 40],
        "materials": ["construction", "mixed", "concrete"],
        "pmin": 500, "pmax": 1100,
        "driveway": False, "sameday": False,
        "score": 82,
    },
    # Washington DC
    {
        "id": "op-fc15-dc-eai",
        "name": "EAI Roll Off",
        "slug": "eai-roll-off",
        "phone": "301-428-0822",
        "email": None,
        "website": "https://eairolloff.com/",
        "desc": "Dumpster and roll-off service for Washington DC, Maryland, and Northern Virginia with 10–30 yard boxes.",
        "city": "city-washington",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 400, "pmax": 850,
        "driveway": False, "sameday": False,
        "score": 82,
    },
    {
        "id": "op-fc15-dc-sel",
        "name": "SEL Hauling",
        "slug": "sel-hauling",
        "phone": "301-330-0983",
        "email": None,
        "website": "https://www.selhauling.com/roll-off-dumpster/",
        "desc": "Roll-off dumpsters within about 25 miles of DC, including 20- and 30-yard open containers.",
        "city": "city-washington",
        "sizes": [20, 30],
        "materials": ["construction", "mixed"],
        "pmin": 400, "pmax": 800,
        "driveway": False, "sameday": False,
        "score": 78,
    },
    # Phoenix extra
    {
        "id": "op-fc15-phx-aros",
        "name": "Arizona Roll-Off Services",
        "slug": "arizona-roll-off-services",
        "phone": "480-725-7240",
        "email": None,
        "website": "https://www.arizonarolloffservices.com/",
        "desc": "Phoenix front-load and roll-off dumpster rental company serving the East Valley.",
        "city": "city-phoenix",
        "sizes": [10, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 650,
        "driveway": False, "sameday": False,
        "score": 82,
    },
    # Baltimore
    {
        "id": "op-fc15-bal-ace",
        "name": "ACE Roll Off",
        "slug": "ace-roll-off",
        "phone": "410-288-3867",
        "email": "acerolloff@288dump.com",
        "website": "https://www.acerolloff.com/",
        "desc": "Locally owned Baltimore dumpster rental with 10–40 yard roll-offs and same-day options.",
        "city": "city-baltimore",
        "sizes": [10, 15, 20, 30, 40],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 750,
        "driveway": True, "sameday": True,
        "score": 85,
    },
    {
        "id": "op-fc15-bal-86",
        "name": "86 Dumpster",
        "slug": "86-dumpster",
        "phone": "443-671-1850",
        "email": "info@86dumpsters.com",
        "website": "https://86dumpster.com/",
        "desc": "White Marsh, Maryland roll-off company serving Baltimore with 10–30 yard dumpsters and published rates from $409.",
        "city": "city-baltimore",
        "sizes": [10, 15, 20, 25, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 409, "pmax": 597,
        "driveway": False, "sameday": False,
        "score": 82,
    },
    # Bonus high-confidence scrapes from earlier Firecrawl work
    {
        "id": "op-fc15-bhm-daddy",
        "name": "Dumpster Daddy",
        "slug": "dumpster-daddy",
        "phone": "205-447-8044",
        "email": None,
        "website": "https://www.dumpsterdaddyal.com/",
        "desc": "Locally owned Birmingham roll-off hauler with 15–40 yard dumpsters and same-day service.",
        "city": "city-birmingham",
        "sizes": [15, 20, 25, 30, 40],
        "materials": ["construction", "mixed", "household", "roofing"],
        "pmin": 325, "pmax": 700,
        "driveway": False, "sameday": True,
        "score": 85,
    },
    {
        "id": "op-fc15-lou-wastenow",
        "name": "Waste Now",
        "slug": "waste-now",
        "phone": "502-969-7684",
        "email": None,
        "website": "https://www.wastenow.com/",
        "desc": "Local Louisville dumpster and porta-potty company for residential and construction jobs.",
        "city": "city-louisville",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 650,
        "driveway": True, "sameday": False,
        "score": 83,
    },
    {
        "id": "op-fc15-msy-engulf",
        "name": "EnGulf Waste",
        "slug": "engulf-waste",
        "phone": "504-429-3867",
        "email": "admin@engulfwaste.com",
        "website": "https://engulfwaste.com/",
        "desc": "New Orleans dumpster rental claiming same-day delivery for homes and construction sites.",
        "city": "city-new-orleans",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 700,
        "driveway": False, "sameday": True,
        "score": 82,
    },
    {
        "id": "op-fc15-pvd-rhody",
        "name": "Rhody Disposal",
        "slug": "rhody-disposal",
        "phone": "401-633-4465",
        "email": "info@rhodydisposal.com",
        "website": "https://www.rhodydisposal.com/",
        "desc": "Rhode Island roll-off and junk removal serving Providence and the surrounding cities.",
        "city": "city-providence",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 700,
        "driveway": False, "sameday": False,
        "score": 82,
    },
    {
        "id": "op-fc15-hfd-talkin",
        "name": "Talkin Trash CT",
        "slug": "talkin-trash-ct",
        "phone": "860-604-1941",
        "email": None,
        "website": "https://www.talkintrashct.com/",
        "desc": "Greater Hartford dumpster rental with driveway-friendly 12–20 yard boxes.",
        "city": "city-hartford",
        "sizes": [12, 15, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 650,
        "driveway": True, "sameday": False,
        "score": 81,
    },
    {
        "id": "op-fc15-hfd-hippo",
        "name": "Hippo Hartford Dumpster Rental",
        "slug": "hippo-hartford-dumpster-rental",
        "phone": "860-502-2519",
        "email": None,
        "website": "https://hippodumpsterct.com/",
        "desc": "Hartford-area 10/15/20 yard dumpster rentals with same-day options.",
        "city": "city-hartford",
        "sizes": [10, 15, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 600,
        "driveway": True, "sameday": True,
        "score": 79,
    },
    {
        "id": "op-fc15-fsd-605",
        "name": "605 Hauling",
        "slug": "605-hauling",
        "phone": "605-553-0711",
        "email": "605hauling@gmail.com",
        "website": "https://www.605hauling.com/",
        "desc": "Sioux Falls driveway-safe dumpsters in 12–20 yard sizes.",
        "city": "city-sioux-falls",
        "sizes": [12, 17, 20],
        "materials": ["construction", "mixed", "household"],
        "pmin": 325, "pmax": 600,
        "driveway": True, "sameday": False,
        "score": 82,
    },
    {
        "id": "op-fc15-mht-ktown",
        "name": "K-Town Disposal",
        "slug": "k-town-disposal",
        "phone": "603-386-0386",
        "email": "info@ktowndisposal.com",
        "website": "https://www.ktowndisposal.com/dumpster-rentals/manchester/",
        "desc": "Manchester, New Hampshire dumpster rentals for homes and job sites.",
        "city": "city-manchester",
        "sizes": [10, 15, 20, 30],
        "materials": ["construction", "mixed", "household"],
        "pmin": 350, "pmax": 700,
        "driveway": False, "sameday": False,
        "score": 80,
    },
]


def esc(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def sql_bool(v: bool) -> str:
    return "1" if v else "0"


def main() -> None:
    lines: list[str] = []
    lines.append("-- High-quality local operators researched 2026-08-15 via Firecrawl search + site scrapes.")
    lines.append("-- Quality bar: own-site phone, local/regional hauler, roll-off dumpsters, not a national broker.")
    lines.append("-- verification_notes document web research; phone insurance/license still recommended.")
    lines.append("")

    used_ids = set()
    used_slugs = set()
    city_ids = set()
    for op in OPS:
        assert op["id"] not in used_ids, op["id"]
        assert op["slug"] not in used_slugs, op["slug"]
        used_ids.add(op["id"])
        used_slugs.add(op["slug"])
        city_ids.add(op["city"])
        city_name, state, lat, lng = CITIES[op["city"]]
        email = esc(op.get("email"))
        lines.append("INSERT OR IGNORE INTO operators (")
        lines.append("  id, name, slug, phone, email, website, description, hq_city, hq_state, hq_lat, hq_lng,")
        lines.append("  pricing_min, pricing_max, pricing_notes, included_tonnage, overage_rate,")
        lines.append("  driveway_suitable, driveway_notes, same_day_capable, is_broker,")
        lines.append("  verification_status, last_verified_at, verified_by, verification_notes,")
        lines.append("  insurance_verified, license_notes, quality_score, is_published, is_demo, claim_status, complimentary_leads_remaining")
        lines.append(") VALUES (")
        lines.append(
            f"  {esc(op['id'])}, {esc(op['name'])}, {esc(op['slug'])}, {esc(op['phone'])}, {email}, {esc(op['website'])},"
        )
        lines.append(f"  {esc(op['desc'])}, {esc(city_name)}, {esc(state)}, {lat}, {lng},")
        pmin = "NULL" if op.get("pmin") is None else str(op["pmin"])
        pmax = "NULL" if op.get("pmax") is None else str(op["pmax"])
        lines.append(f"  {pmin}, {pmax}, NULL, NULL, NULL,")
        lines.append(f"  {sql_bool(op['driveway'])}, NULL, {sql_bool(op['sameday'])}, 0,")
        lines.append(f"  'verified', datetime('now'), 'firecrawl-2026-08-15', {esc(NOTES)},")
        lines.append(f"  0, NULL, {op['score']}, 1, 0, 'unclaimed', 1")
        lines.append(");")
        for y in op["sizes"]:
            sid = f"sz-{op['id']}-{y}"
            lines.append(
                f"INSERT OR IGNORE INTO operator_sizes (id, operator_id, yards) VALUES ({esc(sid)}, {esc(op['id'])}, {y});"
            )
        for m in op["materials"]:
            mid = f"mt-{op['id']}-{m}"
            lines.append(
                f"INSERT OR IGNORE INTO operator_materials (id, operator_id, material) VALUES ({esc(mid)}, {esc(op['id'])}, {esc(m)});"
            )
        said = f"sa-{op['id']}"
        lines.append(
            f"INSERT OR IGNORE INTO operator_service_areas (id, operator_id, city_id, zip) VALUES ({esc(said)}, {esc(op['id'])}, {esc(op['city'])}, NULL);"
        )
        lines.append("")

    # Mark researched metros as homepage/sitemap priority.
    ids = ", ".join(esc(c) for c in sorted(city_ids))
    lines.append(f"UPDATE cities SET is_priority = 1, updated_at = datetime('now') WHERE id IN ({ids});")
    lines.append("")

    out = Path("seed/listicle-operators-metros-2026-08-15.sql")
    out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out} ({len(OPS)} operators, {len(city_ids)} cities)")


if __name__ == "__main__":
    main()
